### PR TITLE
I am interested in using your game on my website. Could you add a license file like the MIT one in this pull request so I know how you want your software used?

### PR DESCRIPTION
**Pull request by jpbida**

### CODE REVIEW

**Comment by rcwestlake** [comment]
@jpbida thanks. I'll take a look. I'm also making a few minor changes to improve the layout. I hadn't looked at this for several months, and want to polish the table layout. I'll be in touch tomorrow or the day after.

**Comment by jpbida** [comment]
Thanks! Actually, I am going to be using these math games or in your case
table generator to teach kids how to code. If you have ideas of what should
be improved create an issue in github and it might get fixed this summer by
one of the students.

**Comment by rcwestlake** [comment]
Cool. Tied up on a project this evening but will set aside an hour tomorrow to take care of this. @jpbida

**Comment by jpbida** [comment]
Thanks!

**Comment by rcwestlake** [comment]
@jpbida Can you make a small change for the license? Change rcwestlake to > Ryan C Westlake

**Pull request closed without merging**
